apiclient/src/as_api/mod.rs
backend/src/auth_service/credentials/keys.rs
backend/src/crypto/ear/keys.rs
backend/src/ds/add_clients.rs
backend/src/ds/add_users.rs
backend/src/ds/api.rs
backend/src/ds/group_state.rs
backend/src/ds/join_connection_group.rs
backend/src/ds/join_group.rs
backend/src/ds/mod.rs
backend/src/ds/update_client.rs
backend/src/messages/client_as.rs
backend/src/messages/client_as_out.rs
backend/src/messages/client_ds.rs
backend/src/messages/client_ds_out.rs
backend/src/qs/mod.rs
coreclient/src/contacts/mod.rs
coreclient/src/conversations/store.rs
coreclient/src/groups/diff.rs
coreclient/src/groups/mod.rs
coreclient/src/groups/store.rs
coreclient/src/users/mod.rs
coreclient/src/users/process.rs
server/tests/mod.rs

Also fixes a small bug and extends the lifecycle test.

Change to key wrapping signature ear keys

---

apiclient/src/ds_api/mod.rs
apiclient/src/qs_api/ws.rs
backend/src/ds/api.rs
backend/src/ds/mod.rs
backend/src/messages/client_ds.rs
backend/src/messages/client_ds_out.rs
coreclient/src/dart_api.rs
server/src/endpoints/ds.rs
server/src/endpoints/mod.rs
server/src/lib.rs
server/src/storage_provider/memory/ds.rs

It's not great a great design all in all, but it's a PoC to see if this fixes the current problem. A more expansive rewrite of the message structure of DS requests would be needed to make the structure nicer.

Refactor DS group id request endpoint

---

applogic/Cargo.toml
applogic/src/dart_api.rs
coreclient/src/users/mod.rs
coreclient/src/users/store.rs
coreclient/src/utils/persistence.rs

Let the client specify the path for DB files.

Set DB path

---

backend/src/auth_service/client_record.rs
backend/src/auth_service/connection_package/persistence.rs
backend/src/auth_service/credentials/intermediate_signing_key.rs
backend/src/auth_service/credentials/mod.rs
backend/src/auth_service/credentials/signing_key.rs
backend/src/auth_service/mod.rs
backend/src/auth_service/opaque.rs
backend/src/auth_service/queue.rs
backend/src/auth_service/user_record.rs
backend/src/ds/group_state/mod.rs
backend/src/ds/group_state/persistence.rs
backend/src/ds/mod.rs
backend/src/ds/process.rs
backend/src/errors.rs
backend/src/infra_service.rs
backend/src/lib.rs
backend/src/qs/add_package.rs
backend/src/qs/client_id_decryption_key.rs
backend/src/qs/client_record.rs
backend/src/qs/errors.rs
backend/src/qs/mod.rs
backend/src/qs/queue.rs
backend/src/qs/signing_key.rs
backend/src/qs/user_record.rs
backend/src/settings.rs
server/src/configurations.rs
server/src/endpoints/qs/push_notification_provider.rs
server/src/main.rs
test_harness/src/utils/mod.rs

Fix the way that the DB connection string is composed

Fix db connection string

---

README.md
apiclient/Cargo.toml
apiclient/src/ds_api/mod.rs
apiclient/src/lib.rs
apiclient/src/qs_api/ws.rs
applogic/Cargo.toml
applogic/src/api/conversations.rs
applogic/src/api/types.rs
applogic/src/api/user/connections.rs
applogic/src/lib.rs
backend/Cargo.toml
backend/src/lib.rs
coreclient/Cargo.toml
coreclient/src/clients/mod.rs
coreclient/src/conversations/messages/mod.rs
coreclient/src/lib.rs
server/Cargo.toml
server/src/lib.rs
types/Cargo.toml
types/src/credentials/mod.rs
types/src/crypto/ear/keys.rs
types/src/crypto/serde_arrays.rs
types/src/lib.rs
types/src/messages/client_ds.rs
types/src/messages/client_qs.rs

docs: add crate descriptions

---

.github/workflows/build.yml
applogic/Cargo.toml

Also add a dedicated job to check if Cargo.lock needs to be updated.

ci: fix missing check out in cargo-machete check

---

prototype/lib/conversation_list_pane/conversation_list.dart
prototype/lib/conversation_list_pane/pane.dart
prototype/lib/conversation_pane/conversation_pane.dart
prototype/lib/messenger_view.dart
prototype/lib/theme/spacings.dart
prototype/lib/theme/theme.dart

* Use relative layout instead of absolute stack positioning
* Introduce a list of spacings constants
* Remove unused Scaffold

chore: fix conversations list item spacings

---

Cargo.lock
backend/src/qs/client_record.rs
backend/src/qs/mod.rs
backend/src/settings.rs
server/Cargo.toml
server/src/endpoints/qs/push_notification_provider.rs
server/src/main.rs
test_harness/src/utils/mod.rs

This PR adds server-side support for Android push notifications through FCM.

feat: Server support for Android push notifications

---

app/flutter_rust_bridge.yaml
app/lib/conversation_list_pane/conversation_list.dart
app/lib/conversation_pane/conversation_content/conversation_content.dart
app/lib/conversation_pane/message_composer.dart
app/lib/core_client.dart
app/lib/navigation/navigation_cubit.dart
app/lib/theme/spacings.dart
applogic/src/api/conversations.rs
applogic/src/api/messages.rs
applogic/src/api/types.rs
coreclient/src/conversations/mod.rs

Also
* Rename `GroupIdBytes` to `GroupId`
* Override `toString` for `ConversationId`/`GroupId` to return the UUID

chore: export ConversationId as UuidValue to Dart

---

app/build.yaml
app/lib/conversation_list_pane/conversation_list.dart
app/lib/conversation_pane/conversation_content/conversation_tile.dart
app/lib/conversation_pane/conversation_content/display_message_tile.dart
app/lib/conversation_pane/conversation_details/connection_details.dart
app/lib/conversation_pane/conversation_details/conversation_details.dart
app/lib/conversation_pane/conversation_details/group_details.dart
app/lib/conversation_pane/conversation_pane.dart
app/lib/conversation_pane/message_composer.dart
app/lib/core_client.dart
app/lib/core_extension.dart
justfile

* Disable generation of freezed when/map methods.
* Extract title, username and description of conversation to extension methods.

chore: replace freezed when with pattern matching

---

.github/workflows/build.yml
justfile

CI: split rust ci job

---

server/src/endpoints/qs/push_notification_provider.rs

We need better logging for OAuth errors.

fix: Parse OAuth & log error response

---

app/analysis_options.yaml
app/lib/conversation_list_pane/conversation_list.dart
app/lib/conversation_pane/conversation_content/text_message_tile.dart
app/lib/conversation_pane/conversation_pane.dart
app/lib/conversation_pane/message_composer.dart

chore: Return SizedBox.shrink instead of Container

---

app/lib/conversation_pane/conversation_details/add_members.dart
app/lib/conversation_pane/conversation_details/add_members_cubit.dart

Split the business logic from the UI in the add members screen.

feat: make add members screen stateless

---

Cargo.lock
Cargo.toml
apiclient/src/lib.rs
apiclient/src/qs_api/tests.rs
coreclient/src/clients/api_clients.rs
server/tests/mod.rs
server/tests/qs/ws.rs
test_harness/src/docker/mod.rs

refactor: reuse http client

---

.github/workflows/ios_build.yml
app/fastlane/Fastfile

This PR selects a different build process for iOS, depending on whether the CI runs on a fork or not.

ci: Fork tolerance for iOS build chain

---

app/android/app/build.gradle
app/android/gradle/wrapper/gradle-wrapper.properties
app/android/settings.gradle

Gradle 8.1.0 does not work with Android Studio 2024.2.

chore: update gradle

---

applogic/src/background_execution/processing.rs

Extends the logging for panics that occur in background mode.

chore: More information on panic in background mode

---

app/lib/message_list/text_message_tile.dart

Instead of helper methods, we use classes to build widgets. This is the recommended approach.

refactor: use widgets in text message tile

---

applogic/src/api/user_cubit.rs

Condition for checking whether we are in the conversation list was wrong.

fix: suppress notifications in conversation list

---

applogic/src/api/user_cubit.rs

Websocket handler in user cubit can be stopped normally. In this case, we have to exit the handler. This regression was introduced in #382.

fix: handle stopping websocket normally

---

README.md
justfile

Removes an unnecessary step to build in the app on macOS.

docs: Fix macOS steps

---

apiclient/src/ds_api/mod.rs
backend/src/ds/group_state/mod.rs
backend/src/ds/process.rs
server/src/endpoints/ds.rs
types/src/errors/mod.rs
types/src/messages/client_ds.rs
types/src/messages/client_ds_out.rs

chore: remove unused DS handler

---

coreclient/src/clients/add_contact.rs
coreclient/src/clients/connection_establishment.rs
coreclient/src/clients/process/process_as.rs
types/src/credentials/mod.rs

Also includes some refactoring of the various CEP structs.

chore: include recipient id in CEP signature

---

Cargo.lock
Cargo.toml
README.md
common/.gitignore
common/Cargo.toml
common/benches/argon_pow.rs
common/src/lib.rs
common/src/pow/mod.rs
common/src/rate_limiter/mod.rs

Separate crate for common code of both client & server

feat: Introduce common crate

---

app/lib/core/api/attachments_repository.dart
app/lib/message_list/text_message_tile.dart
applogic/src/api/attachments_repository.rs

Also show an error icon if the attachment download fails.

fix: infinite download loop

---

Cargo.toml

fix: disable neon for blake3 to fix android release

---

app/lib/attachments/attachment_image.dart
app/lib/attachments/attachment_image_provider.dart
app/lib/attachments/attachments.dart
app/lib/core/api/attachments_repository.dart
app/lib/core/frb_generated.dart
app/lib/core/frb_generated.io.dart
app/lib/core/frb_generated.web.dart
app/lib/message_list/text_message_tile.dart
app/test/message_list/goldens/message_list_attachments.png
app/test/message_list/message_list_test.dart
applogic/src/api/attachments_repository.rs
applogic/src/frb_generated.rs
coreclient/src/clients/attachment/download.rs

Also 
* Move `AttachmentImage` widget into a dedicated file.
* Constrain attachment image max height to 300 pixels.

feat: show progress indicator when downloading attachments

---

app/lib/conversation_details/connection_details.dart
app/lib/conversation_details/member_details_screen.dart
app/lib/l10n/app_en.arb
app/lib/l10n/app_localizations.dart
app/lib/l10n/app_localizations_en.dart
app/test/conversation_details/connection_details_test.dart
app/test/conversation_details/goldens/connection_details.linux.png
app/test/conversation_details/goldens/connection_details.macos.png
app/test/conversation_details/goldens/connection_details.windows.png
app/test/conversation_details/goldens/members_details.linux.png
app/test/conversation_details/goldens/members_details.macos.png
app/test/conversation_details/goldens/members_details.windows.png
app/test/conversation_details/member_details_test.dart
app/test/mocks.dart

Also adjust the spacings and fonts in member and connection details views to match.

test: add snapshot tests for connection and member details

---

app/lib/chat_list/create_chat_view.dart
app/lib/l10n/app_en.arb
app/lib/l10n/app_localizations.dart
app/lib/l10n/app_localizations_de.dart
app/lib/l10n/app_localizations_en.dart
app/lib/l10n/app_localizations_fr.dart
app/lib/registration/display_name_picture.dart
app/lib/registration/server_choice.dart
app/lib/user/add_user_handle_screen.dart
app/lib/user/edit_display_name_screen.dart

The following forms were changed to support submitting on enter:
* Add user handle screen (also disable autocorrect)
* Server choice screen
* Display name picture screen
* New connection/group dialog

feat: submit forms on enter

---

applogic/src/messages.rs
coreclient/.sqlx/query-601a9276fd78f32ebed85cee5d489e3352a34a992bb04062ef2d4f945f0bc070.json
coreclient/.sqlx/query-8cfdfc12e51fd295690779a4b3904afe8c6c3f32470610112f48d8bb74a3165f.json
coreclient/src/clients/block_contact.rs
coreclient/src/clients/message.rs
coreclient/src/clients/mod.rs
coreclient/src/clients/process/process_as.rs
coreclient/src/clients/process/process_qs.rs
coreclient/src/clients/user_profile.rs
coreclient/src/groups/mod.rs
coreclient/src/lib.rs
server/tests/integration.rs
test_harness/src/utils/setup.rs

- All messages from blocked contacts, including text messages, profile
updates, and group invitations are dropped.
- Sending messages or delivery receipts to blocked contacts is not
possible.
- Updates to own profile are no longer communicated to blocked contacts.
- Invitations from blocked contacts are dropped.

feat: implement actual blocking of blocked contacts

---

app/lib/l10n/app_en.arb
app/lib/l10n/app_localizations.dart
app/lib/l10n/app_localizations_en.dart
app/test/user/goldens/contact_us_screen_validation.linux.png
app/test/user/goldens/contact_us_screen_validation.macos.png
app/test/user/goldens/contact_us_screen_validation.windows.png

Changing UX text in "Contact Us" feature

feat: update copy of "contact us" feature

---

app/ios/NotificationService/NotificationService.swift
app/ios/Podfile.lock
applogic/src/background_execution/swift_api.rs

Fixes a regression introduced in #378 and makes the Swift/Rust FFI more robust.

chore: NSE robustness improvements & regression fix

---

app/lib/app.dart
app/lib/chat_details/chat_screen.dart
app/lib/core/api/navigation_cubit.dart
app/lib/core/frb_generated.dart
app/lib/navigation/navigation_cubit.dart
applogic/src/api/navigation_cubit.rs
applogic/src/frb_generated.rs

Introduced a bug s.t. it is not possible to navigate back to the same chat.
This reverts commit 1be46e2af50c24477bfcf8e1a321f8a288f913ed.

Revert "fix: race between showing a chat and mounting the chat details cubit (#703)"
