server/.sqlx/query-98a7c1eb916f19befa1b8afcc8c5b0c135d28651554ca8e6410d29759449d1cd.json, server/src/storage_provider/postgres/auth_service.rs, server/src/storage_provider/postgres/ds.rs, server/src/storage_provider/postgres/mod.rs, server/src/storage_provider/postgres/qs.rs, server/tests/database_initialization.rs, test_harness/src/docker.rs
This PR adds a check at server startup that ensures that the AS/DS/QS databases are only created if they aren't already present.
=> Check for existing DB before creating a new one.

applogic/src/api/mobile_logging.rs
When setting a new stream sink in `SendToDartLogger`, we lock the global
rw lock for writing. However, if the lock already contained a sink, it
was droppen at the same line when replacing it. A stream sink logs a
message on drop, and therefore `SendToDartLogger` tries to lock the
global rw lock again, this time for reading. The lock is not reentrant,
so it deadlocks.
This makes sure we drop the previous sink *after* unlocking the rw lock.
In particular, this fixes hot restart in Flutter.
Fixes https://github.com/phnx-im/infra/issues/225
=> fix: deadlock when replacing logging stream sink

compose.yaml, justfile
Also add a simple docker compose file with postgres.
```
Available recipes:
generate-db-certs    # generate postgres TLS certificates
generate-flutter-ffi # generate Rust and Dart flutter bridge files
init-db              # run postgres via docker compose and apply migrations
```
Note: usage of just in CI is not part of this commit.
Related #232
=> chore: bootstrap justfile

.github/workflows/android_build.yml, justfile, prototype/pubspec.lock
This PR works towards #232 & #233 by migrating the Android CI build process.
=> chore: Android justfile

prototype/devtools_options.yaml, prototype/integration_test/simple_test.dart, prototype/lib/app.dart, prototype/lib/conversation_list_pane/conversation_list.dart, prototype/lib/conversation_list_pane/footer.dart, prototype/lib/conversation_list_pane/pane.dart, prototype/lib/conversation_list_pane/top.dart, prototype/lib/conversation_pane/conversation_content/conversation_content.dart, prototype/lib/conversation_pane/conversation_content/text_message_tile.dart, prototype/lib/conversation_pane/conversation_details/add_members.dart, prototype/lib/conversation_pane/conversation_details/connection_details.dart, prototype/lib/conversation_pane/conversation_details/conversation_details.dart, prototype/lib/conversation_pane/conversation_details/group_details.dart, prototype/lib/conversation_pane/conversation_details/member_details.dart, prototype/lib/conversation_pane/conversation_pane.dart, prototype/lib/conversation_pane/message_composer.dart, prototype/lib/core_client.dart, prototype/lib/homescreen.dart, prototype/lib/main.dart, prototype/lib/registration/display_name_picture.dart, prototype/lib/settings/developer.dart, prototype/lib/settings/user.dart, prototype/lib/theme/theme.dart, prototype/lib/theme/theme_data.dart, prototype/pubspec.lock, prototype/pubspec.yaml
This is a preparation for introducing a custom router and splitting the
core client into separate feature-specific classes.
The `CoreClient` instance can now be access from `context` via a
provider with `context.read<CoreClient>`. There is also a shortcut
available via an extension of `BuildContext`: `context.coreClient`.
Also:
* Move `App` into a separate file
* Configure Flutter logging in main
* Init Flutter Rust Bridge in main
* Move out theme data into a separate file
=> refactor: replace core client singleton by provider

justfile
`flutter_rust_bridge_codegen` uses the `RUSTLFAGS = ["--cfg", "frb_expand"]` which are different from the default `RUSTFLAGS` of `cargo build|test|clippy`. That's why running the codegen invalidates the cargo cache, and running `cargo build` etc. invalidates the codegen cache.
In this commit, we specify a dedicated cargo target directory for the codegen. Also, we don't delete the flutter cache anymore.
=> chore: don't invalidate cargo cache on frb codegen

app/lib/app.dart, app/lib/conversation_list_pane/conversation_list.dart, app/lib/conversation_list_pane/pane.dart, app/lib/conversation_list_pane/top.dart, app/lib/conversation_pane/conversation_content/text_message_tile.dart, app/lib/conversation_pane/conversation_details/group_details.dart, app/lib/conversation_pane/conversation_details/member_details.dart, app/lib/core_client.dart, app/lib/intro_screen.dart, app/lib/loadable_user_cubit.dart, app/lib/registration/registration_cubit.dart, app/lib/settings/user.dart, app/lib/user_cubit.dart, applogic/src/api/types.rs, applogic/src/api/user/connections.rs, applogic/src/api/user/mod.rs, applogic/src/api/user/user_cubit.rs, applogic/src/lib.rs, applogic/src/util.rs, justfile
The `UserCubit` is accessible in the whole app, after a user is loaded. All widgets that access the user information e.g. their user name or profile, are doing it via the `UserCubit`. In particular, it makes them stateless and they automatically re-rendered when the user information is changed.
Implementation details:
The cubit is implemented on the Rust side, and
is exposed to Flutter via frb. On the Flutter side, the `UserCubit` is a wrapper around the `UserCubit` in Rust. Currently, it is not possible to require that a from-Rust generated class in Dart impements a specific interface. When this will be possible, the wrapper can be removed. ([1])
Also:
* rename `ObservableUser` to `LoadableUserCubit`
* CI: don't flutter clean and pub get in `just frb-generate`
[1]: …
=> refactor: expose the user via a provider in the whole app

justfile
Fixes #240.
Unfortunately, only literal strings are supported, but it's unlikely the working directory will change frequently.
=> chore: Justfile working directory

applogic/src/api/message_list_cubit.rs, coreclient/Cargo.toml, coreclient/src/clients/conversations.rs, coreclient/src/clients/message.rs, coreclient/src/clients/mod.rs, coreclient/src/clients/own_client_info/mod.rs, coreclient/src/clients/own_client_info/persistence.rs, coreclient/src/clients/persistence.rs, coreclient/src/clients/process/process_qs.rs, coreclient/src/clients/store.rs, coreclient/src/contacts/mod.rs, coreclient/src/contacts/persistence.rs, coreclient/src/conversations/messages/mod.rs, coreclient/src/conversations/messages/persistence.rs, coreclient/src/conversations/mod.rs, coreclient/src/conversations/persistence.rs, coreclient/src/groups/client_auth_info/mod.rs, coreclient/src/groups/client_auth_info/persistence.rs, coreclient/src/user_profiles/mod.rs, coreclient/src/user_profiles/persistence.rs, test_harness/src/utils/setup.rs, types/src/credentials/mod.rs, types/src/crypto/ear/keys.rs, types/src/crypto/kdf/keys.rs, types/src/crypto/secrets.rs, types/src/crypto/signatures/signable.rs
Testing revealed two bugs
1. Staged group membership update did not work on
`GroupMembership::merge_for_group` due to unique key constraint.
2. `Conversation::mark_as_read_until_message_id` failed when given
message id did not exist.
Addition break up long SQL query strings. Rust formatter does not 
format lines longer than 100 chars.
=> chore: test persistence layer in client

.github/workflows/build.yml, .github/workflows/docker_tests.yml, backend/.env, justfile
The variable DATABASE_URL is predefined in the backend/.env file. This conflicts with the prepared compile-time sqlx metadata, since the environment variable takes precedence over the metadata. In particular, the rust compilation fails when the database server is not running.
=> fix: local compilation without running postgres DB

apiclient/src/ds_api/mod.rs, apiclient/src/qs_api/mod.rs, apiclient/src/version.rs, backend/src/ds/process.rs, server/src/endpoints/ds.rs, server/src/endpoints/qs/mod.rs, types/src/errors/mod.rs, types/src/errors/qs.rs, types/src/errors/version.rs, types/src/identifiers/mod.rs, types/src/messages/client_ds.rs, types/src/messages/client_ds_out.rs, types/src/messages/client_qs.rs, types/src/messages/client_qs_out.rs, types/src/messages/mod.rs
If the DS backend does not support the API version used by the client,
it responds with a `406 Not Acceptable` status and includes an
`x-accepted-api-versions` header containing a comma-separated list of
supported API versions.
The client handles the `406` status code by attempting to resend the
request using the highest supported API version, if possible.
The server always responds with the API version from the client's
request. The latest supported API version is stored in the client's
memory.
Additionally, non-group API requests are moved into
`ClientToDsMessageTbs` from the top-level `DsMessageTypeIn/Out` struct.
The top-level struct is replaced by `ClientToDsMessageOut` /
`VerifiableClientToDsMessage`, enabling versioning for non-group API
requests as well.
=> feat: version and negotiate DS API between client and server 

Cargo.lock, Cargo.toml, apiclient/Cargo.toml, apiclient/src/qs_api/ws.rs, backend/Cargo.toml, coreclient/Cargo.toml, server/Cargo.toml, types/Cargo.toml, types/src/crypto/secrets.rs
All dependencies are upgraded except the following:
- rand 0.9: the latest version is not yet used in most of our
dependencies, and so would introduce a dupicate dependency.
- tokio-tungstenite 0.26: uses rand 0.9
- rusqlite 0.33: uses sqlite 0.30 which conflicts with sqlx
- derive_more 2.0: would introduce a duplicate dependency
=> chore: upgrade dependencies

coreclient/src/conversations/messages/persistence.rs, coreclient/src/mimi_content/mod.rs
This is a breaking change. Previous messages still exist in the database, but will be rendered as an error:
=> refactor: improve versioning for messages

server/src/configurations.rs, test_harness/src/utils/mod.rs
In particular, this allows to run the test as a standalone binary.
=> test: embed configuration into the test runner

applogic/src/api/user.rs, coreclient/src/clients/message.rs, coreclient/src/clients/mod.rs, coreclient/src/clients/process/process_qs.rs, coreclient/src/store/notification.rs, server/tests/mod.rs
This bug was introduced during the CoreClient to SQLx port (#291).
Previously, the store notifier triggered *before* the transaction was
committed, meaning notifications were received during the transaction.
However, the database connection was wrapped in a mutex, allowing only a
single connection to be used at a time.
Now, with concurrent database access, this leads to a race condition.
The fix is to ensure we use `with_transaction_and_notifier`, which
triggers notifications *after* the transaction is committed.
Additionally, this commit fixes user loading. Instead of giving up after
the first client record, we now continue trying until no more client
records remain.
=> fix: race between transactions and notifier

app/lib/core/api/markdown.dart, app/lib/core/api/markdown.freezed.dart, app/lib/core/api/types.dart, app/lib/core/api/types.freezed.dart, app/test/message_list/message_cubit_test.dart, applogic/src/api/markdown.rs, applogic/src/api/types.rs
Before comparison of Lists inside UiConversationMessage was done via object identity. Now it is done via deep collection equality by switching the type to freezed.
=> fix: equality of UiConversationMessage

app/lib/message_list/message_list_view.dart, app/test/message_list/message_list_view_test.dart
The comparison of the visibility key was based on the idenity comparison and not the equality of the ids.
Closes #375
=> perf: jank when showing/hiding keyboard in a conversation

coreclient/src/user_profiles/persistence.rs
Avoid sending store notifications when the user profile is already stored (on ignore conflict).
Closes #369
=> chore: store notifications for already stored user profiles

server/src/endpoints/auth_service.rs
Before, we returned 500 internal server error.
Closes #231
=> fix: return 409 conflict when user already exists

Cargo.lock, Cargo.toml, server/Cargo.toml, server/src/lib.rs
Rate limiting is based on a leaky bucket algorithm per IP, with a burst of 20 requests and replenishment every 500ms.
Note: For rate limiting to work correctly behind a reverse proxy, the proxy must include the client IP in one of the following headers: `x-forwarded-for`, `x-real-ip`, or `forwarded`.
Closes #419
=> feat: rate limit grpc services

app/lib/app.dart, app/lib/conversation_details/conversation_details_screen.dart, app/lib/conversation_details/conversation_screen.dart
In particular, this also allows to use the conversation details state from any screen, as long as a conversation is open.
=> refactor: only mount the conversation details cubit once

applogic/src/api/user_cubit.rs, deployment/ingress-nginx-values.yaml, server/src/lib.rs
Connections to the backend were terminated after 10 seconds of inactivity. Turns out the load balancer of upcloud has a configuration parameter for this. Now we set it to 1 hour.
Also 
* Fix listen cancellation in user cubit.
* Add http2 keep alive on the server-side. This prevents the reverse proxy to terminate connections to the backend when it is idle.
=> fix: idle connection termination

app/lib/message_list/message_renderer.dart
=> fix: padding and alignment for checkboxes

.gitattributes, .github/workflows/flutter_test.yml, app/l10n.yaml, app/lib/app.dart, app/lib/conversation_details/add_members_screen.dart, app/lib/conversation_details/conversation_details_screen.dart, app/lib/conversation_details/conversation_screen.dart, app/lib/conversation_details/member_details_screen.dart, app/lib/conversation_list/conversation_list_footer.dart, app/lib/intro_screen.dart, app/lib/l10n/app_en.arb, app/lib/l10n/app_en.arb.license, app/lib/l10n/app_localizations.dart, app/lib/l10n/app_localizations_en.dart, app/lib/l10n/l10n.dart, app/lib/user/add_user_handle_screen.dart, app/lib/user/edit_display_name_screen.dart, app/lib/user/user_settings_screen.dart, app/pubspec.lock, app/pubspec.yaml, app/test/conversation/conversation_screen_view_test.dart, app/test/home_screen_test.dart, app/test/user/add_user_handle_screen_test.dart, app/test/user/edit_display_name_screen_test.dart, app/test/user/goldens/user_settings_screen_no_handles.png, app/test/user/user_settings_screen_test.dart, justfile
This commit adds support for localizing the app's UI text.  It introduces the `intl` package and generates localized strings for English. All relevant UI text has been updated to use localized strings.
The generated localization files are checked in to the repository. CI checks that the localization files are up to date.
Closes #509
=> feat: add localization support

Cargo.lock, apiclient/src/ds_api/grpc.rs, apiclient/src/ds_api/mod.rs, backend/Cargo.toml, backend/src/ds/attachments.rs, backend/src/ds/grpc.rs, backend/src/ds/mod.rs, backend/src/ds/storage.rs, backend/src/settings.rs, common/src/identifiers/attachment.rs, common/src/identifiers/mod.rs, common/src/time.rs, compose.yaml, protos/api/auth_service/v1/auth_service.proto, protos/api/common/v1/common.proto, protos/api/delivery_service/v1/delivery_service.proto, protos/src/auth_service/convert.rs, protos/src/common/convert.rs, protos/src/delivery_service/sign.rs, server/configuration/local.yaml, server/src/main.rs
This commit adds support for attachments to the delivery service.
Attachments are provisioned using a new `ProvisionAttachment` gRPC
method. This method returns a pre-signed URL for uploading the
attachment, along with the necessary headers. A new `GetAttachmentUrl`
method retrieves a pre-signed URL for downloading attachments.
Minio is added to docker compose as a development storage backend.
=> feat: add attachments backend API

.github/workflows/flutter_test.yml, justfile
Also merge `flutter-test` and `flutter-check-localizations` in CI into a
single job to avoid installing Flutter SDK twice in CI. Additionally,
add a step to check that the Flutter lockfile is up to date. Also 
remove unneeded Rust toolchain setup because it is not used.
=> CI: fix dart being formatted differently in CI

app/rust_builder/android/build.gradle, app/rust_builder/cargokit/build_pod.sh, app/rust_builder/cargokit/build_tool/lib/src/builder.dart, app/rust_builder/cargokit/build_tool/lib/src/environment.dart, app/rust_builder/cargokit/build_tool/lib/src/options.dart, app/rust_builder/cargokit/cmake/cargokit.cmake, app/rust_builder/cargokit/gradle/plugin.gradle, app/rust_builder/ios/phnxapplogic.podspec, app/rust_builder/linux/CMakeLists.txt, app/rust_builder/macos/phnxapplogic.podspec, app/rust_builder/windows/CMakeLists.txt, applogic/src/notifications.rs, rust-toolchain.toml
CargoKit used stable toolchain by default ignoring installed toolchain
in CI.
Rust toolchain is now specified in rust-toolchain.toml file.
Additionally, cargokit has a new environment variable
CARGOKIT_TOOLCHAIN_TOML which is the path to the rust-toolchain.toml
file. It reads the toolchain from the file and uses it cargo build.
Caveat: the version specified in CI workflow files and rust-toolchain.toml
needs to be in sync.
=> fix: use Rust toolchain in cargokit as specified in rust-toolchain.toml

app/rust_builder/cargokit/build_tool/lib/src/android_environment.dart
Tested in Android Emulator with 16 KB pages support enabled.
Also see <https://android-developers.googleblog.com/2025/05/prepare-play-apps-for-devices-with-16kb-page-size.html>
=> build: support 16 KB page size on Android

app/lib/core/api/user_settings_cubit.dart, app/lib/core/api/user_settings_cubit.freezed.dart, app/lib/core/frb_generated.dart, app/lib/core/frb_generated.io.dart, app/lib/core/frb_generated.web.dart, app/lib/user/user_settings_screen.dart, app/lib/util/interface_scale.dart, applogic/src/api/user_settings_cubit.rs, applogic/src/frb_generated.rs, coreclient/src/store/impl.rs, coreclient/src/store/mod.rs
When we are on Linux and there is no user setting for interface scale, we
automatically set the interface scale to 1.5 on 4k displays. Also, do
not scale linearly if there is no setting. This is important, since
other platforms (e.g. Android) might have non-linear scaling.
=> feat: scale automatically on Linux/4k
